server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. Routing untuk Frontend (React SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Routing untuk API Backend
    location /api/ {
        proxy_pass http://yomu-backend-staging:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Routing untuk OAuth2
    location /oauth2/ {
        proxy_pass http://yomu-backend-staging:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Routing untuk Login/Callback
    location /login/ {
        proxy_pass http://yomu-backend-staging:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}