name: Frontend CI (Lint & Build)

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Menjalankan ESLint sebagai Code Quality Tool
      - name: Run Lint
        run: npm run lint

      # Memastikan aplikasi bisa di-build dengan sukses sebelum CD Vercel jalan
      - name: Build check
        run: npm run build
  deploy-staging:
    name: Continuous Deployment (Staging)
    runs-on: ubuntu-latest
    needs: [ check-quality ]

    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dummy Vercel Deployment Script
        run: |
          echo "✅ CI Gateway Passed! Memulai deployment ke Vercel Staging Environment..."
          echo "🌐 URL Target: https://staging.yomu.vercel.app"
          echo "Menjalankan perintah: vercel pull --environment=preview"
          echo "Menjalankan perintah: vercel build"
          echo "Menjalankan perintah: vercel deploy --prebuilt"
          echo "🎉 Deployment Staging Berhasil! (Dummy Script)"
  deploy-production:
    name: Continuous Deployment (Production)
    runs-on: ubuntu-latest
    needs: [ check-quality ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Dummy Vercel Production Deploy
        run: |
          echo "🚀 CI sukses! Deploy ke PRODUCTION Environment..."
          echo "🌐 URL Target: https://yomu.info"